// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIJAVh_s8osNTOs37XZ13CNKk8Or33Ng',
    appId: '1:346591048869:web:c85e2d3492c118c38f094c',
    messagingSenderId: '346591048869',
    projectId: 'flutter-test-43b51',
    authDomain: 'flutter-test-43b51.firebaseapp.com',
    storageBucket: 'flutter-test-43b51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7F2z3-rtpV5JpbSvP6vtTrUh6R82YNis',
    appId: '1:346591048869:android:a51fbdc49de700968f094c',
    messagingSenderId: '346591048869',
    projectId: 'flutter-test-43b51',
    storageBucket: 'flutter-test-43b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmjpFhtTnj2v6EYjLLokmPehRRUwKHOI',
    appId: '1:346591048869:ios:f008a74e4974fd028f094c',
    messagingSenderId: '346591048869',
    projectId: 'flutter-test-43b51',
    storageBucket: 'flutter-test-43b51.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmjpFhtTnj2v6EYjLLokmPehRRUwKHOI',
    appId: '1:346591048869:ios:f008a74e4974fd028f094c',
    messagingSenderId: '346591048869',
    projectId: 'flutter-test-43b51',
    storageBucket: 'flutter-test-43b51.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
